services:
  - type: web
    name: monito-client
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://monito-api-hrtu4.ondigitalocean.app/api/v1/*
      - type: rewrite
        source: /*
        destination: /index.html