import { z } from "zod";

/**
 * Zod schema for validating a raw telemetry event sent by the SDK.
 *
 * Fields set by the server (not expected from the client):
 *  - event_id   - generated by the ingestion controller
 *  - tenant_id  - resolved from the API key
 *  - project_id - resolved from the API key
 *
 * Fields with server-side defaults:
 *  - timestamp  - falls back to Date.now() if the SDK omits it
 */
export const IngestionSchema = z.object({
    //  Server-generated fields 
    event_id: z.string().uuid("event_id must be a valid UUID"),
    tenant_id: z.string().uuid("tenant_id must be a valid UUID"),
    project_id: z.string().uuid("project_id must be a valid UUID"),

    //  SDK-supplied fields 
    service: z
        .string()
        .min(1, "Service name is required")
        .max(100),

    endpoint: z
        .string()
        .min(1, "Endpoint is required")
        .max(500),

    method: z.enum(["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"]),

    status: z
        .number()
        .int({ message: "HTTP status must be an integer" })
        .min(100, "Invalid HTTP status code")
        .max(599, "Invalid HTTP status code"),

    latency: z
        .number()
        .nonnegative("Latency must be 0 or greater"),

    environment: z
        .string()
        .min(1, "Environment is required")
        .max(100),

    timestamp: z
        .string()
        .datetime("Timestamp must be a valid ISO 8601 datetime"),

    error: z
        .string()
        .min(1, "Error string cannot be empty")
        .max(2000)
        .nullable()
        .optional(),
}).strict();

export type IngestionType = z.infer<typeof IngestionSchema>;

/**
 * Safely parses an unknown payload against the IngestionSchema.
 * @param {unknown} data - Raw request body
 * @returns {SafeParseReturnType} Zod safe-parse result
 */
export const validateIngestion = (data: unknown) => {
    return IngestionSchema.safeParse(data);
};
